./mycd / abc
./mycd /abc/def ghi
./mycd /abc/def ..
./mycd /abc/def /abc
./mycd /abc/def /abc/klm
./mycd /abc/def ../..
./mycd /abc/def ../../..
./mycd /abc/def .
./mycd /abc/def ..klm
./mycd /abc/def //////
./mycd /abc/def ......
./mycd /abc/def ../gh///../klm/.
./mycd /a/b/c /b/c/.././././../lolo999
